version: '3.9'
services:
  db:
    image: mysql:8
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=your_db
      - MYSQL_USER=your_user
      - MYSQL_PASSWORD=your_password
      - MYSQL_ROOT_PASSWORD=your_password
      - MYSQL_HOST=db
    ports:
      - "3307:3306"  
  web:         
    build: 
      context: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: mywebsite 
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./app:/app 
    environment:
      - DB_HOST=db
      - DB_NAME=your_db
      - DB_USER=your_user
      - DB_PASS=your_password
    